name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-documentation:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: "v0-x86_64-unknown-linux-gnu"

      - name: Build Cargo docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/
