name: "GitHub Pages - Rust doc"

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@440166417b42442c6114aaa895094f0db7de9b78
