name: "Rust CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@main

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@29197a38ef3741064f47b623ede0c1ad22402c57

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@29197a38ef3741064f47b623ede0c1ad22402c57

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@29197a38ef3741064f47b623ede0c1ad22402c57
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}
